type Capability = "layout" | "accessibility" | "local-storage" | "keyboard-navigation" | "validation" | "content-filter" | "content-compare" | "hide-elements" | "reorganize";
type RegistryPatch = { id: string; name: string; summary: string; version: string; scope: { hosts: string[]; paths: string[] }; capabilities: Capability[]; download: string; sha256: string; verification: { status: "verified"; operations: number; assertions: number }; compatibility?: { status: "healthy" | "drifted" | "unreachable"; checkedAt: string; pageUrl: string; healthy: number; total: number; fingerprint: string } };
type Registry = { schemaVersion: 1; patches: RegistryPatch[] };
const labels: Record<Capability, string> = { "accessibility":"Accessibility", "content-filter":"Filters", "content-compare":"Compare", "hide-elements":"Remove clutter", "keyboard-navigation":"Keyboard", "layout":"Mobile layout", "local-storage":"Keep progress", "reorganize":"Reorganize", "validation":"Validation" };
const grid = document.querySelector<HTMLDivElement>("#patch-grid")!; const empty = document.querySelector<HTMLParagraphElement>("#empty-state")!; const search = document.querySelector<HTMLInputElement>("#patch-search")!; const summary = document.querySelector<HTMLElement>("#registry-summary")!; const template = document.querySelector<HTMLTemplateElement>("#patch-card-template")!;
let patches: RegistryPatch[] = []; let selected = "all";
function relativeDate(value: string) { const hours = Math.floor(Math.max(0, Date.now() - new Date(value).getTime()) / 3_600_000); return hours < 1 ? "just now" : hours < 24 ? `${hours}h ago` : `${Math.floor(hours / 24)}d ago`; }
function card(patch: RegistryPatch) { const fragment = template.content.cloneNode(true) as DocumentFragment; const text = (selector: string, value: string) => { fragment.querySelector<HTMLElement>(selector)!.textContent = value; }; text(".version", `v${patch.version}`); text("h3",patch.name); text(".summary",patch.summary); text(".scope",`${patch.scope.hosts.join(", ")} · ${patch.scope.paths.join(", ")}`); text(".checked",patch.compatibility ? relativeDate(patch.compatibility.checkedAt) : "Not monitored"); text(".health",patch.compatibility ? `${patch.compatibility.healthy}/${patch.compatibility.total} healthy` : "Preflight required"); text(".hash",`SHA-256 ${patch.sha256}`); text(".operations",`${patch.verification.operations} tested transformations · ${patch.verification.assertions} assertions`); const capabilities = fragment.querySelector<HTMLDivElement>(".capabilities")!; patch.capabilities.slice(0,5).forEach((capability) => { const chip=document.createElement("span"); chip.textContent=labels[capability]; capabilities.append(chip); }); const download=fragment.querySelector<HTMLAnchorElement>(".download")!; download.href=patch.download; download.download=patch.download.split("/").pop() ?? "patch-the-web.json"; const link=fragment.querySelector<HTMLAnchorElement>(".page-link")!; if(patch.compatibility) link.href=patch.compatibility.pageUrl; else link.hidden=true; const button=fragment.querySelector<HTMLButtonElement>(".details")!; const detail=fragment.querySelector<HTMLElement>(".receipt-detail")!; button.addEventListener("click",()=>{ const open=button.getAttribute("aria-expanded")==="true"; button.setAttribute("aria-expanded",String(!open)); detail.hidden=open; button.textContent=open ? "View receipt" : "Hide receipt"; }); return fragment; }
function render() { const query=search.value.trim().toLowerCase(); const result=patches.filter((patch)=>{const text=`${patch.name} ${patch.summary} ${patch.scope.hosts.join(" ")} ${patch.capabilities.join(" ")}`.toLowerCase(); return (selected === "all" || patch.capabilities.includes(selected as Capability)) && text.includes(query);}); grid.replaceChildren(); empty.hidden=result.length>0; result.forEach((patch)=>grid.append(card(patch))); }
document.querySelectorAll<HTMLButtonElement>(".filter-chip").forEach((button)=>button.addEventListener("click",()=>{selected=button.dataset.filter ?? "all"; document.querySelectorAll<HTMLButtonElement>(".filter-chip").forEach((chip)=>{const active=chip===button; chip.classList.toggle("is-active",active); chip.setAttribute("aria-pressed",String(active));}); render();})); search.addEventListener("input",render);
async function load() { try { const response=await fetch("/registry/index.json",{cache:"no-store"}); const registry=await response.json() as Registry; if(!response.ok || registry.schemaVersion!==1 || !Array.isArray(registry.patches)) throw new Error("Registry unavailable"); patches=registry.patches.filter((patch)=>patch.verification.status === "verified" && patch.compatibility?.status === "healthy"); const operations=patches.reduce((total,patch)=>total+patch.verification.operations,0); summary.textContent=`${patches.length} verified repairs · ${operations} tested transformations · every selector rechecked before install`; grid.setAttribute("aria-busy","false"); render(); } catch { summary.textContent="Registry receipt is temporarily unavailable."; grid.setAttribute("aria-busy","false"); empty.hidden=false; empty.textContent="Could not load the registry. Try again shortly."; } } void load();
